Villa/taller ros
Troyanos-Robotics-Club/documentation-obsidian pull request #16
Opened 2023-11-05 17:01 UTC by david-villanueva-02

2023-11-06 16:38 UTC, G00Z-G00Z commented on Excalidraw/Estructura_general_ROS.excalidraw.md
Excelente uso de Excalidraw!!

2023-11-06 16:44 UTC, G00Z-G00Z requested changes
Hay unos problemas del rendering, pero el contenido se ve bien

2023-11-06 16:44 UTC, G00Z-G00Z commented on talleres/Taller ROS/Presentacion Taller ROS.md
> +## Recap🔙
Overflow aqui

2023-11-06 16:44 UTC, G00Z-G00Z commented on talleres/Taller ROS/Presentacion Taller ROS.md
> +## Ahora siguen ustedes!😎
Overflow aca tmb

2023-11-06 16:44 UTC, G00Z-G00Z commented on talleres/Taller ROS/Presentacion Taller ROS.md
> +	subgraph CustomSize [1500px,1400px]
Creo que el customize size no está saliendo, porque salen los pixeles en la imagen de mermaid

2023-11-06 16:44 UTC, G00Z-G00Z commented on talleres/Taller ROS/Presentacion Taller ROS.md
> +graph TD
Recomiendo que uses un flowchart en vez de graph, es más sencillo en mi opinión

2023-11-06 16:44 UTC, G00Z-G00Z commented on talleres/Taller ROS/Presentacion Taller ROS.md
> +### Nodo RPi
Overflow

2023-11-06 16:44 UTC, G00Z-G00Z commented on talleres/Taller ROS/Presentacion Taller ROS.md
> +### Solución Nodo 1
Overflow. Pone un espacio entre bloques (headings, texto, bloques de código, etc)

2023-11-06 16:44 UTC, G00Z-G00Z commented on talleres/Taller ROS/Presentacion Taller ROS.md
> +### Solución Nodo 1
En general esta slide se ve mal, creo que los espacios hicieron que el rendering se rompiera. Intenta separar las slides

2023-11-07 00:40 UTC, david-villanueva-02 commented on talleres/Taller ROS/Presentacion Taller ROS.md
> +	subgraph CustomSize [1500px,1400px]
no supe corregir eso.

2023-11-07 00:53 UTC, david-villanueva-02 commented on talleres/Taller ROS/Presentacion Taller ROS.md
> +### Solución Nodo 1
Okay lo corregiré

2023-11-07 17:56 UTC, G00Z-G00Z approved these changes
Parece que todo está bien

2023-11-07 18:00 UTC, merged